### ISSUE TITLE
Idea to show the stats by injecting it on the page

### ISSUE THREAD

**Issue by boritopalito** [spruce04/Dreaming-Spanish-Toolkit#3]
Currently, the Dreaming Spanish Toolkit Extension calculates the time watched in the current month and displays it in the pop-up. However, it would be more convenient for users if the results were directly visible on the progress page without requiring them to click the pop-up. This issue suggests enhancing the extension to inject HTML into the progress page and display the time watched results there.

### Suggested Solution:

1. Modify the extension's code to inject HTML elements into the progress page whenever it is loaded.
2. Design a visually appealing and informative display format to show the time watched in the current month.
3. Retrieve the calculated time watched data from the extension and dynamically update the injected HTML elements.
4. Ensure the injected HTML elements blend seamlessly with the existing design and layout of the progress page.

### How would the result look like?

![Schermafbeelding 2023-07-12 124324](https://github.com/spruce04/Dreaming-Spanish-Toolkit/assets/28512031/cd474fe8-7754-4749-86af-30190b862dc5)

Let me know what you think about this idea :)

**Comment by spruce04** [comment]
Yeah, it seems good to me! Definitely much more convenient than having to open the extension every time you want to look at the stats. I'm happy for you to do it if you want to, or I can try do it as well but probably won't have the time for the next couple weeks. Either works let me know which you'd rather.

**Comment by boritopalito** [comment]
Thank you for your response. I can definitely take a look in the upcoming days.

**Comment by spruce04** [comment]
Going to start working on this now that I have time again. Not sure if you're still interested in the project, but just thought I'd let you know.
